# version: '3.8'

x-airflow-common:
  &airflow-common
  # image: apache/airflow:2.8.1
  image: apache/airflow:2.8.1-python3.10
  environment:
    &airflow-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__DEFAULT_TIMEZONE: Asia/Kolkata   # # Set the timezone to India Standard Time (IST)
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    AIRFLOW__WEBSERVER__AUTH_BACKEND: 'airflow.api.auth.backend.session'
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW_UID: "${AIRFLOW_UID}"  
    DATA_DIR: /opt/airflow/data
    MONGODB_HOST: "${MONGODB_HOST}"
    MONGODB_DAATBASE: "${MONGODB_DAATBASE}"
    MONGODB_COLLECTION: "${MONGODB_COLLECTION}"
  volumes:
     - ./dags:/opt/airflow/dags
     - ./plugins:/opt/airflow/plugins
     - ./logs:/opt/airflow/logs
     - ./data:/opt/airflow/data
     - ./requirements.txt:/opt/airflow/requirements.txt
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command: -c "
      pip uninstall -y bson &&
      rm -rf /home/airflow/.local/lib/python3.10/site-packages/bson* &&
      pip install --force-reinstall pymongo &&
      pip install -r /opt/airflow/requirements.txt && airflow db init && airflow users create \
      --username admin \
      --password admin \
      --firstname Air \
      --lastname Flow \
      --role Admin \
      --email abdullahsyed940@gmail.com.com"

  webserver:
    <<: *airflow-common
    ports:
      - "8080:8080"
    command: bash -c "
      pip uninstall -y bson &&
      rm -rf /home/airflow/.local/lib/python3.10/site-packages/bson* &&
      pip install --force-reinstall pymongo &&
      pip install -r /opt/airflow/requirements.txt && airflow webserver"
    depends_on:
      - airflow-init

  scheduler:
    <<: *airflow-common
    command: bash -c "
      pip uninstall -y bson &&
      rm -rf /home/airflow/.local/lib/python3.10/site-packages/bson* &&
      pip install --force-reinstall pymongo &&
      pip install -r /opt/airflow/requirements.txt && airflow scheduler"
    depends_on:
      - airflow-init

volumes:
  postgres-db-volume:
